### ISSUE TITLE
Stylus does not work under OS Ubuntu

### ISSUE THREAD

**Issue by Yashila** [buzinas/vscode-stylus#7]
Hello all!

I have tried to install Stylus in vscode under Ubuntu and it does not work. After hours of trying I installed it under windows and everthing is fine there.

Could you please make it work also for ubuntu? I would love to continue working with VSCODE on Ubuntu.
Thank you

Yashi

**Comment by buzinas** [comment]
I'm a Windows user as well, but I'll be glad to accept PR's for that.

**Comment by moqmar** [comment]
Oh, good to know that amended & force-pushed commits still show up in issues... :smiley:
